// Generated by Selenium IDE

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.support.ui.ExpectedCondition;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import javax.swing.text.Element;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.TimeUnit;

public class SimpleSearchTest {
    private static ChromeDriver driver;
    private static JavascriptExecutor js;
    private static HashMap<String, Object> vars;
    private static final SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
    WebDriverWait wait = new WebDriverWait(driver, 5);

    @BeforeAll
    public static void setUp() {
        ChromeOptions chromeOptions = new ChromeOptions();
        chromeOptions.setExperimentalOption("debuggerAddress", "127.0.0.1:9222");
        driver = new ChromeDriver(chromeOptions);
//        driver.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        Date date = new Date();
        System.out.println("before all " + dateFormat.format(date));
    }

    @AfterAll
    public static void tearDown() {
        driver.quit();
        Date date = new Date();
        System.out.println("after all " + dateFormat.format(date));
    }

    public String waitForWindow(int timeout) {
        try {
            Thread.sleep(timeout);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        Set<String> whNow = driver.getWindowHandles();
        Set<String> whThen = (Set<String>) vars.get("window_handles");
        if (whNow.size() > whThen.size()) {
            whNow.removeAll(whThen);
        }
        return whNow.iterator().next();
    }

    @Test
    public void simpleSearch() {
        driver.get("https://www.baidu.com/");
        driver.manage().window().setSize(new Dimension(1117, 927));
        driver.findElement(By.id("kw")).click();
        driver.findElement(By.id("kw")).sendKeys("我的祖国");

        WebElement elementSU = wait.until(ExpectedConditions.presenceOfElementLocated(By.id("su")));
        elementSU.click();

//        driver.findElement(By.id("su")).click();
        vars.put("window_handles", driver.getWindowHandles());
        vars.put("win653", waitForWindow(2000));
        driver.findElement(By.xpath("//div[@id=\'1\']/h3/a/em")).click();
        vars.put("win653", waitForWindow(2000));
        vars.put("root", driver.getWindowHandle());
        driver.switchTo().window(vars.get("win653").toString());
        driver.close();
        driver.switchTo().window(vars.get("root").toString());
        driver.close();
//        driver.switchTo().window(vars.get("undefined").toString());
    }
}
